### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 39769 (char 39768)

### ISSUE THREAD

**Issue by keita69** [keita69/autoTradeBitBank#1]
### 事象発生時のバージョン
https://github.com/keita69/autoTradeBitBank/tree/2b6f84a40b5b0e96fc122460d4bc6480b01c0609

### トレース
```
Traceback (most recent call last):
  File "bitbankAutoOrder.py", line 696, in <module>
    ao.order_buy_sell()
  File "bitbankAutoOrder.py", line 658, in order_buy_sell
    buy_order_result = self.buy_order()
  File "bitbankAutoOrder.py", line 519, in buy_order
    if(self.is_buy_order()):
  File "bitbankAutoOrder.py", line 477, in is_buy_order
    "1min", n_short, n_long)
  File "bitbankAutoOrder.py", line 117, in get_ema_cross_status
    df_ema = self.get_ema(candle_type, n_short, n_long)
r/lib/python3.5/json/decoder.py" File "bitbankAutoOrder.py", line 93, in get_ema
    df_ema = self.get_candlestick(n_long, candle_type)
  File "bitbankAutoOrder.py", line 57, in get_candlestick
    "xrp_jpy", candle_type, yyyymmdd)
  File "/usr/local/lib/python3.5/dist-packages/python_bitbankcc/public_api.py", line 59, in get_candlestick
    return self._query(self.end_point + path)
  File "/usr/local/lib/python3.5/dist-packages/python_bitbankcc/public_api.py", line 42, in _query
    return error_parser(response.json())
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 39769 (char 39768)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bitbankAutoOrder.py", line 718, in <module>
    raise BaseException
BaseException
```

### ログファイル
[nohup.txt](https://github.com/keita69/autoTradeBitBank/files/2042571/nohup.txt)

**Comment by keita69** [comment]
再現せず！
