### ISSUE TITLE
Exception: エラーコード: 50010 内容: ご指定の注文はキャンセルできません

### ISSUE THREAD

**Issue by keita69** [keita69/autoTradeBitBank#2]
### ソース
https://github.com/keita69/autoTradeBitBank/tree/8d889445e67f8bac260a1279a93b952afc0d5089

### トレース
```
2018-05-27 16:59:31,342 %(levelname)s 【損切判定されました 現在値：66.604 損切値：65.658 】
Traceback (most recent call last):
  File "bitbankAutoOrder.py", line 698, in <module>
    ao.order_buy_sell()
  File "bitbankAutoOrder.py", line 661, in order_buy_sell
    buy_order_result, _ = self.sell_order(buy_order_result)
  File "bitbankAutoOrder.py", line 615, in sell_order
    sell_order_status["order_id"]  # 注文ID
  File "/usr/local/lib/python3.5/dist-packages/python_bitbankcc/private_api.py", line 106, in cancel_order
    'order_id': order_id
  File "/usr/local/lib/python3.5/dist-packages/python_bitbankcc/private_api.py", line 76, in _post_query
    return error_parser(response.json())
  File "/usr/local/lib/python3.5/dist-packages/python_bitbankcc/utils.py", line 33, in error_parser
    raise Exception(message)
Exception: エラーコード: 50010 内容: ご指定の注文はキャンセルできません

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bitbankAutoOrder.py", line 720, in <module>
    raise BaseException
BaseException
```

### ログ
[nohup.txt](https://github.com/keita69/autoTradeBitBank/files/2043069/nohup.txt)

**Comment by keita69** [comment]
指値注文が約定していることが原因。
これをキャンセルすればOK！！
