### ISSUE TITLE
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

### ISSUE THREAD

**Issue by keita69** [keita69/autoTradeBitBank#5]
##  ソース
https://github.com/keita69/autoTradeBitBank/tree/379f3a81d11dd41076ff86644d40ba7c0f035049

## トレース
```
2018-05-29 00:00:00,712 %(levelname)s yyyymmdd=20180529 candle_type=1min
Traceback (most recent call last):
  File "bitbankAutoOrder.py", line 736, in <module>
    ao.order_buy_sell()
  File "bitbankAutoOrder.py", line 698, in order_buy_sell
    buy_order_result = self.buy_order()
  File "bitbankAutoOrder.py", line 556, in buy_order
    if(self.is_buy_order()):
  File "bitbankAutoOrder.py", line 514, in is_buy_order
    "1min", n_short, n_long)
  File "bitbankAutoOrder.py", line 157, in get_ema_cross_status
    clf.fit(x, y)        # 予測モデルを作成
  File "/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/base.py", line 482, in fit
    y_numeric=True, multi_output=True)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bitbankAutoOrder.py", line 758, in <module>
    raise BaseException
BaseException
```

## ログ
[nohup.out.zip](https://github.com/keita69/autoTradeBitBank/files/2046359/nohup.out.zip)

**Comment by keita69** [comment]
UTC 0:00 に日付が変わることによって一瞬データがなくなることが原因と判明。
